name: Test React Native nightly build for Expo Modules

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [main]
    paths:
      - .github/workflows/test-react-native-nightly.yml
      - packages/create-expo-nightly/**
  pull_request:
    paths:
      - .github/workflows/test-react-native-nightly.yml
      - packages/create-expo-nightly/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ios-build:
    strategy:
      fail-fast: true
      matrix:
        build-type: [debug, release]
    runs-on: macos-15
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v5
      - name: 🔨 Switch to Xcode 26.2
        run: sudo xcode-select --switch /Applications/Xcode_26.2.app
      - name: 🍺 Install required tools
        run: brew install watchman || true
      - name: 🚀 Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: 💎 Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: 💎 Install Ruby gems
        run: gem install cocoapods xcpretty
      - name: ♻️ Restore workspace node modules
        uses: actions/cache/restore@v4
        id: workspace-modules-cache
        with:
          path: |
            node_modules
            packages/*/node_modules
            packages/@expo/*/node_modules
          key: ${{ runner.os }}-workspace-modules-${{ hashFiles('yarn.lock') }}
      - name: 🧶 Install node modules in root dir
        if: steps.workspace-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: ⭐️ Create test-nightlies Project
        run: bun src/index.ts --expo-repo ${{ github.workspace }} --no-install ${{ runner.temp }}
        working-directory: packages/create-expo-nightly
      - name: 🍏 Query available simulator device ID
        run: |
          DEVICE_ID=$(xcrun simctl list devices available -j | jq -r '.devices | to_entries[] | select(.value | length > 0) | select(.key | startswith("com.apple.CoreSimulator.SimRuntime.iOS")) | .value[] | select(.isAvailable == true) | .udid' | head -n 1)
          echo "DEVICE_ID=$DEVICE_ID" >> $GITHUB_ENV
      - name: 🍏 Build iOS Project
        run: |
          pod install --project-directory=ios
          xcodebuild -workspace ios/testnightlies.xcworkspace -scheme testnightlies -configuration $CONFIGURATION -sdk iphonesimulator -destination "id=$DEVICE_ID" -derivedDataPath "ios/build" | xcpretty
        shell: bash
        working-directory: ${{ runner.temp }}/test-nightlies
        env:
          NODE_ENV: production
          CONFIGURATION: ${{ matrix.build-type == 'release' && 'Release' || 'Debug' }}
      - name: 📸 Upload builds
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'workflow_dispatch' && matrix.build-type == 'release' }}
        with:
          name: ios-builds-arch-${{ matrix.build-type }}
          path: ${{ runner.temp }}/test-nightlies/ios/build/**/testnightlies.app/
      - name: 🔔 Notify on Slack
        uses: slackapi/slack-github-action@v2.1.1
        if: failure() && (github.event_name == 'schedule' || github.event_name == 'push')
        with:
          webhook: ${{ secrets.slack_webhook_ios }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "❌ *Build Failed* in *iOS Build Job*\n*Repository:* ${{ github.repository }}\n*Link:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run Details>"
            }

  android-build:
    strategy:
      fail-fast: true
      matrix:
        build-type: [debug, release]
    runs-on: ubuntu-24.04
    env:
      ORG_GRADLE_PROJECT_reactNativeArchitectures: x86_64
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4096m -XX:MaxMetaspaceSize=4096m"
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v5
      - name: 🚀 Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: 🔨 Use JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: ♻️ Restore workspace node modules
        uses: actions/cache/restore@v4
        id: workspace-modules-cache
        with:
          path: |
            node_modules
            packages/*/node_modules
            packages/@expo/*/node_modules
          key: ${{ runner.os }}-workspace-modules-${{ hashFiles('yarn.lock') }}
      - name: 🧶 Install node modules in root dir
        if: steps.workspace-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: ⭐️ Create test-nightlies Project
        run: bun src/index.ts --expo-repo ${{ github.workspace }} --no-install ${{ runner.temp }}
        working-directory: packages/create-expo-nightly
      - name: 🤖 Build Android project
        run: |
          cd android && ./gradlew ":app:assemble$VARIANT"
        shell: bash
        working-directory: ${{ runner.temp }}/test-nightlies
        env:
          NODE_ENV: production
          VARIANT: ${{ matrix.build-type == 'release' && 'Release' || 'Debug' }}
      - name: 📸 Upload builds
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'workflow_dispatch' && matrix.build-type == 'release' }}
        with:
          name: android-builds-${{ matrix.build-type }}
          path: ${{ runner.temp }}/test-nightlies/android/app/build/outputs/apk/
      - name: 🔔 Notify on Slack
        uses: slackapi/slack-github-action@v2.1.1
        if: failure() && (github.event_name == 'schedule' || github.event_name == 'push')
        with:
          webhook: ${{ secrets.slack_webhook_android }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "❌ *Build Failed* in *Android Build Job*\n*Repository:* ${{ github.repository }}\n*Link:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run Details>"
            }
  - patterns: ['packages/expo-dev-menu-interface/**']
    mentions: ['lukmccall', 'douglowder', 'gabrieldonadel']
  - patterns: ['packages/expo-device/**']
    mentions: ['ide', 'alanjhughes']
  - patterns: ['packages/expo-doctor/**']
    mentions: ['keith-kurak']
  - patterns: ['packages/expo-document-picker/**']
    mentions: ['lukmccall', 'alanjhughes']
  - patterns: ['packages/expo-env-info/**']
    mentions: ['bycedric']
  - patterns: ['packages/expo-file-system/**']
    mentions: ['brentvatne', 'Kudo', 'ide', 'aleqsio']
  - patterns: ['packages/expo-font/**']
    mentions: ['alanjhughes', 'vonovak', 'tsapeta']
  - patterns: ['packages/expo-gl/**']
    mentions: ['lukmccall', 'tsapeta']
  - patterns: ['packages/expo-haptics/**']
    mentions: ['lukmccall']
  - patterns: ['packages/expo-image/**']
    mentions: ['lukmccall', 'aleqsio', 'tsapeta']
  - patterns: ['packages/expo-image-manipulator/**']
    mentions: ['lukmccall', 'alanjhughes']
  - patterns: ['packages/expo-image-picker/**']
    mentions: ['lukmccall', 'alanjhughes']
  - patterns: ['packages/expo-insights/**']
    mentions: ['lukmccall', 'jakex7']
  - patterns: ['packages/expo-intent-launcher/**']
    mentions: ['Kudo', 'jakex7']
  - patterns: ['packages/expo-keep-awake/**']
    mentions: ['brentvatne', 'Kudo']
  - patterns: ['packages/expo-linear-gradient/**']
    mentions: ['alanjhughes']
  - patterns: ['packages/expo-local-authentication/**']
    mentions: ['behenate']
  - patterns: ['packages/expo-localization/**']
    mentions: ['EvanBacon', 'aleqsio']
  - patterns: ['packages/expo-location/**']
    mentions: ['behenate', 'lukmccall']
  - patterns: ['packages/expo-mail-composer/**']
    mentions: ['brentvatne', 'alanjhughes']
  - patterns: ['packages/expo-maps/**']
    mentions: ['jakex7', 'alanjhughes']
  - patterns: ['packages/expo-manifests/**']
    mentions: ['wschurman']
  - patterns: ['packages/expo-media-library/**']
    mentions: ['behenate', 'alanjhughes']
  - patterns: ['packages/expo-mesh-gradient/**']
    mentions: ['jakex7']
  - patterns: ['packages/expo-module-scripts/**']
    mentions: ['ide']
  - patterns: ['packages/expo-module-template/**']
    mentions: ['aleqsio', 'EvanBacon']
  - patterns: ['packages/expo-module-template-local/**']
    mentions: ['aleqsio']
  - patterns: ['packages/expo-modules-autolinking/**']
    mentions: ['Kudo', 'lukmccall', 'kitten']
  - patterns: ['packages/expo-modules-core/**']
    mentions: ['Kudo', 'lukmccall', 'tsapeta']
  - patterns: ['packages/expo-modules-test-core/**']
    mentions: ['aleqsio', 'lukmccall', 'tsapeta']
  - patterns: ['packages/expo-navigation-bar/**']
    mentions: ['EvanBacon']
  - patterns: ['packages/expo-network/**']
    mentions: ['ide', 'lukmccall']
  - patterns: ['packages/expo-network-addons/**']
    mentions: ['Kudo']
  - patterns: ['packages/expo-notifications/**']
    mentions: ['douglowder', 'vonovak']
  - patterns: ['packages/expo-print/**']
    mentions: ['lukmccall']
  - patterns: ['packages/expo-processing/**']
    mentions: ['EvanBacon']
  - patterns: ['packages/expo-router/**']
    mentions: ['EvanBacon', 'ubax', 'hassankhan', 'kitten']
  - patterns: ['packages/expo-screen-capture/**']
    mentions: ['behenate']
  - patterns: ['packages/expo-screen-orientation/**']
    mentions: ['lukmccall']
  - patterns: ['packages/expo-secure-store/**']
    mentions: ['Kudo', 'behenate']
  - patterns: ['packages/expo-sensors/**']
    mentions: ['lukmccall', 'behenate']
  - patterns: ['packages/expo-server/**']
    mentions: ['bycedric', 'kitten']
  - patterns: ['packages/expo-sharing/**']
    mentions: ['alanjhughes']
  - patterns: ['packages/expo-sms/**']
    mentions: ['alanjhughes']
  - patterns: ['packages/expo-speech/**']
    mentions: ['lukmccall', 'alanjhughes']
  - patterns: ['packages/expo-splash-screen/**']
    mentions: ['alanjhughes']
  - patterns: ['packages/expo-sqlite/**']
    mentions: ['Kudo', 'alanjhughes']
  - patterns: ['packages/expo-standard-web-crypto/**']
    mentions: ['EvanBacon']
  - patterns: ['packages/expo-status-bar/**']
    mentions: ['brentvatne']
  - patterns: ['packages/expo-store-review/**']
    mentions: ['EvanBacon']
  - patterns: ['packages/expo-structured-headers/**']
    mentions: ['douglowder']
  - patterns: ['packages/expo-symbols/**']
    mentions: ['alanjhughes']
  - patterns: ['packages/expo-system-ui/**']
    mentions: ['EvanBacon']
  - patterns: ['packages/expo-task-manager/**']
    mentions: ['chrfalch', 'bycedric']
  - patterns: ['packages/expo-tracking-transparency/**']
    mentions: ['alanjhughes']
  - patterns: ['packages/expo-ui/**']
    mentions: ['aleqsio', 'behenate', 'douglowder']
  - patterns: ['packages/expo-updates/**']
    mentions: ['Kudo', 'alanjhughes', 'douglowder', 'wschurman']
  - patterns: ['packages/expo-updates-interface/**']
    mentions: ['Kudo', 'alanjhughes', 'douglowder', 'wschurman']
  - patterns: ['packages/expo-video/**']
    mentions: ['lukmccall', 'aleqsio', 'behenate']
  - patterns: ['packages/expo-video-thumbnails/**']
    mentions: ['behenate', 'tsapeta']
  - patterns: ['packages/expo-web-browser/**']
    mentions: ['alanjhughes']
  - patterns: ['packages/expo-yarn-workspaces/**']
    mentions: ['bycedric']
  - patterns: ['packages/html-elements/**']
    mentions: ['EvanBacon']
  - patterns: ['packages/install-expo-modules/**']
    mentions: ['Kudo']
  - patterns: ['packages/jest-expo/**']
    mentions: ['brentvatne', 'EvanBacon']
  - patterns: ['packages/jest-expo-puppeteer/**']
    mentions: ['ide', 'EvanBacon']
  - patterns: ['packages/patch-project/**']
    mentions: ['Kudo']
  - patterns: ['packages/pod-install/**']
    mentions: ['bycedric', 'EvanBacon']
  - patterns: ['packages/uri-scheme/**']
    mentions: ['bycedric', 'EvanBacon']
  - patterns:
      [
        'packages/eslint-config-expo/**',
        'packages/eslint-config-universe/**',
        'packages/eslint-plugin-expo/**',
      ]
    mentions: ['kadikraman']
  - patterns: ['tools/**']
    mentions: ['Kudo', 'tsapeta']
  - patterns: ['packages/expo-widgets/**']
    mentions: ['jakex7']
